### ISSUE TITLE
Customize My Own Theme Colors

### ISSUE THREAD

**Issue by AlanThinks** [8base/boost#137]
**Is your feature request related to a problem? Please describe.**
I would like to create my own colors and set them as variables that Boost can use, in order to use them in my components such as <NavigationPlate color="MY_COLOR"/> or ...color="PRIMARY" in such a way that "PRIMARY" was my own color that is not in the **Boost Palette** already.

**Describe the solution you'd like**
Perhaps there is already a way to customize or overwrite the **defaultTheme.js**?

**Comment by ej9x** [comment]
Yes, you can. I have added usage with a custom theme to the doc https://github.com/8base/boost#usage-with-custom-theme
Actually `defaultTheme` just an object. You could change it how you want.
