### ISSUE TITLE
<TextAreaField> missing ::placeholder style

### ISSUE THREAD

**Issue by AlanThinks** [8base/boost#143]
**Describe the bug**
`<TextAreaField>::placeholder `style(color) is not the same as the rest of the inputs

**Screenshots**
![screen shot 2018-12-03 at 6 59 03 pm](https://user-images.githubusercontent.com/28021164/49409261-d55c8700-f72d-11e8-91a3-e0676c5618fb.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome

**Comment by zouxuoz** [comment]
@AlanThinks fixed
