### ISSUE TITLE
Incorrect Documentation on DateInputField

### ISSUE THREAD

**Issue by alacret** [8base/boost#146]
**Describe the bug**
Documentaion doesn't show the correct information about the component.

**To Reproduce**
1. Go to Boost Storybook
2. Click on DateInput or DateInputField
3. See the incorrect documentation

**Expected behavior**
Correct documentation on how to use the field, and import statement

**Screenshots**
![screen shot 2018-12-09 at 3 47 30 pm](https://user-images.githubusercontent.com/918895/49702754-1a6b3800-fbca-11e8-9b77-73b4a33a41b1.png)

![screen shot 2018-12-09 at 3 47 36 pm](https://user-images.githubusercontent.com/918895/49702755-1ccd9200-fbca-11e8-91b3-a2b860b5bab8.png)

**Comment by zouxuoz** [comment]
@alacret https://8base.github.io/boost/?selectedKind=Components%2FDateInputField&selectedStory=common
