### ISSUE TITLE
Incomplete <Icon> Documentation

### ISSUE THREAD

**Issue by AlanThinks** [8base/boost#153]
**Describe the bug**
The `<Icons>` listed in the storybook number 18, but the ones I count when looking inside `glyphs` file inside boost are over 30 icons

**Screenshots**
Storybook:
https://8base.github.io/boost/?selectedKind=ATOMS%2FTYPOGRAPHY%2FIcon&selectedStory=all%20icons&full=0&addons=1&stories=1&panelRight=0
![image](https://user-images.githubusercontent.com/28021164/49745224-75556b80-fc6c-11e8-9fb7-c76dc426f065.png)

Glyphs File:
https://github.com/8base/boost/tree/master/src/atoms/typography/Icon/glyphs
![image](https://user-images.githubusercontent.com/28021164/49745256-87370e80-fc6c-11e8-80cd-889c6316d474.png)

**Comment by zouxuoz** [comment]
@AlanThinks fixed https://8base.github.io/boost/?selectedKind=Components%2FIcon&selectedStory=all%20icons
