### ISSUE TITLE
<TextAreaField> Label disappears when you first click input field

### ISSUE THREAD

**Issue by AlanThinks** [8base/boost#177]
**Describe the bug**
The `<TextAreaField>` Label disappears momentarily when you first click the input field to begin typing

**Screenshots**
![textareafielderror](https://user-images.githubusercontent.com/28021164/50426866-b81b6400-0866-11e9-9947-1c5c4d1a647f.gif)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by lesha1201** [comment]
@zouxuoz Can you reproduce this? I think it should be closed

**Comment by zouxuoz** [comment]
@lesha1201 can't reproduce that
